#-------------------------------
# Site Settings
title: Haining
description: A student-led public service project that helps children explore traditional Chinese herbs with stories, visuals, and data.
logo: # You can add own logo. For example '/images/logo.png'.
logo_dark:


#-------------------------------
# Color Scheme Settings
color_scheme:
  default: dark # Default theme applied on the first visit (options: "light" or "dark")
  toggle: true # Enable theme toggle

# Enables or disables the theme toggle functionality:
# - true: Users can switch between light and dark modes using a toggle button.
#          The site will remember their choice for future visits.
# - false: The theme will always use the default mode specified above,
#          and the toggle button will not be displayed.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: 'Home'
      url: '/'
    - title: 'Videos'
      url: '/videos/'
    - title: 'Data Stories'
      url: '/Data Stories/'
    - title: 'Pages'
    - title: 'About'
      url: '/about/'



#-------------------------------
# Author Settings
author:
  author_name: Haining Wang
  author_avatar: /images/01-1.jpg


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_avatar: /images/01-1.jpg
  hero_title: Hi! I’m Haining
  hero_subtitle: Student, herbal storyteller, and community explorer
  hero_description: |
    I’m a high school student passionate about traditional Chinese medicine and children’s education. This site is a personal project to share herbal knowledge through stories, vlogs, and visuals.

    Here, I explore how ancient wisdom meets modern learning — making herbs approachable for kids using creative tools and real-life experiences. Dive in and discover more 🌿
  hero_image: /images/01.jpg
  hero_image_caption: Learning with care, growing with curiosity
  hero_button_text: Let’s Work Together
  hero_button_link: '/contact/'


# Logos
logos:
  enable: true
  logos_title: Nerd Stuff
  logo_image:
    - alt: "Game Boy"
      image: "/images/1000.jpg"
    - alt: "Super Nintendo"
      image: "/images/1001.jpg"
    - alt: "Keyboard"
      image: "/images/1002.jpg"
    - alt: "Headphones"
      image: "/images/1003.jpg"
    - alt: "Mouse"
      image: "/images/1004.jpg"


#-------------------------------
# Section Blog Settings
blog:
  enable: true
  blog_title: Herb & Story




#-------------------------------
# Videos Section Settings
videos_section:
  enable: true
  videos_section_title: Latest Videos




#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Learn Herbs, One Leaf at a Time 🍃
  mailchimp_description: Each month, we share gentle stories, hands-on herb guides, and illustrated lessons designed to help kids and families connect with traditional Chinese medicine in a modern, friendly way.
  mailchimp_identifier: https://hainingstudio.github.io/
  mailchimp_input_text: Enter your email to get updates 🌱
  mailchimp_button_text: Subscribe for Stories



#-------------------------------
# Footer Settings
footer_description: I share stories, knowledge, and interactive tools that help children and families explore the world of traditional Chinese medicine in a safe, engaging, and science-informed way. This project is my way of giving back—rooted in family, guided by curiosity, and open to all who care.


#-------------------------------
# Social Settings
social:
- {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
- {icon: "fa-brands fa-facebook", name: "Facebook", link: "https://facebook.com"}
- {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
- {icon: "fa-brands fa-reddit-alien", name: "Reddit", link: "https://reddit.com"}
- {icon: "fa-brands fa-github", name: "Github", link: "https://github.com"}
- {icon: "fa-solid fa-rss", name: "Rss", link: "/feed.xml"}

# Example of adding a new link to the sidebar and footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: your@email.com # Add your form_id
  button_text: Send Now

# NOTE
# Coderon theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: true
  disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test
  disqus_title: Start the conversation
  disqus_button_text: Show Comments


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
